---
- name: Install Prereqs
  hosts: webservers
  remote_user: pi

  tasks:
  - name: Update apt cache and install git
    apt:
      name: git
      state: latest
      update_cache: yes
      autoclean: yes
    become: yes
